### ISSUE TITLE
Are pnpm workspaces supported?

### ISSUE THREAD

**Issue by Kazimazi** [nzbr/pnpm2nix-nzbr#29]
Tried to package an [example repo](https://github.com/DavidWells/pnpm-workspaces-example), but couldn't make it work.

**Comment by nzbr** [comment]
Workspaces seem to work if you set `installInPlace = true;`. You might need to overwrite the buildPhase as well if you need something more complex than `pnpm run <something>`. Haven't tested it with the example repo though

**Comment by nzbr** [comment]
This works for the example repo:
```nix
mkPnpmPackage {
  src = ./.;
  installInPlace = true;
  script = "-r build";

  distDir = "."; # Copy everything to the output
};
```
I just had to run `pnpm i` once, because the repo still has a version 5 lockfile but pnpm2nix can only handle version 6 lockfiles

**Comment by Kazimazi** [comment]
Awesome, thank you!
